'use strict';
// The allele universe of the Alpha collection, as counts. 178 heritable alleles over six loci,
// plus Ears, which is the sex locus and not a trait.
//
// Counts only. Every dominance fact in the game is derived from them at load by windowsFor(), so
// there is exactly one place where the one-third rule lives and no second table to keep in step.
// Regenerate with tools/adventure/alleles.js if the collection is ever extended.

const TOTAL = 3333;

const COUNTS = {
  Background: {
    "Purple": 242,
    "Yellow": 229,
    "Black": 225,
    "Grey": 218,
    "Red": 216,
    "Cool Green": 214,
    "Blocks": 212,
    "Sky Blue": 210,
    "Blue": 205,
    "Pink": 191,
    "Lemon": 188,
    "Blue Sky": 157,
    "Pink Sky": 130,
    "Emerald": 129,
    "Fuchsia": 118,
    "Sea Green": 116,
    "Bitcoin Orange": 92,
    "Night Sky": 90,
    "Punk": 61,
    "Zombie": 46,
    "Spectrum": 44,
  },
  Body: {
    "Sand": 191,
    "Dark Grey": 180,
    "Grey": 178,
    "Brown": 174,
    "Chocolate": 167,
    "Green": 166,
    "Ginger": 164,
    "Bitcoin Orange": 161,
    "White": 160,
    "Burmilla": 153,
    "Caramel": 152,
    "Red": 152,
    "Yellow": 152,
    "Au Lait": 150,
    "Cream": 147,
    "Blue": 145,
    "Pink": 145,
    "Bengal": 96,
    "Tortie": 71,
    "Harlequin Cream": 48,
    "Harlequin Ginger": 47,
    "Light Calico": 45,
    "Harlequin Earth": 44,
    "Harlequin Pink": 40,
    "Tiger": 39,
    "Oreo": 38,
    "Harlequin Lava": 31,
    "Cow": 27,
    "Harlequin Lime": 26,
    "Harlequin Monster": 23,
    "Harlequin Poison": 11,
    "Harlequin Lava Lamp": 10,
  },
  Collar: {
    "Red": 249,
    "Purple": 235,
    "Yellow": 234,
    "Green": 233,
    "Emerald": 231,
    "Bitcoin Orange": 228,
    "Black": 226,
    "Fuchsia": 226,
    "Sea Green": 220,
    "Dark Grey": 219,
    "Lemon": 218,
    "Blue": 212,
    "Sky Blue": 211,
    "Pink": 196,
    "White": 195,
  },
  Face: {
    "Sour": 111,
    "Perplexed Tiny Big Eyes": 110,
    "Cheeky": 108,
    "Happy Big Eyes": 103,
    "Happy": 102,
    "Sleeping Tif": 102,
    "Lover": 99,
    "Grumpy": 98,
    "Orange Glasses": 98,
    "Perplexed Tif": 98,
    "Satisfied": 98,
    "Perplexed Big Eyes": 97,
    "Perplexed Large": 97,
    "Sleepy Drool": 97,
    "UwU": 97,
    "sessalG D3": 97,
    "Crying": 96,
    "Perplexed Medium": 96,
    "Perplexed Small": 96,
    "Cooler": 91,
    "Stunned": 91,
    "3D Glasses": 90,
    "Laughing": 90,
    "Stunned Tif": 90,
    "Happy Big Mouth": 89,
    "Pink Glasses": 88,
    "Perplexed Tiny": 87,
    "Grumpier": 84,
    "Sky Blue Glasses": 81,
    "Happy Tif": 80,
    "Cool": 77,
    "Shiny Eyes Happy": 52,
    "Shiny Eyes Drool": 51,
    "Rainbow Glasses": 49,
    "Big Laughing": 36,
    "Double Shocked": 36,
    "In Love": 36,
    "Cyber Punk": 26,
    "Lazer": 25,
    "Super Happy": 22,
    "Demon": 21,
    "Super Laser": 17,
    "Old TV": 15,
    "Rainbow": 9,
  },
  Rune: {
    "Fire Purple": 67,
    "Hope Blue": 67,
    "Ride Blue": 67,
    "Fire Yellow": 64,
    "Runestone Green": 64,
    "Sun Red": 64,
    "Runestone Yellow": 62,
    "Ride Purple": 61,
    "Birch Red": 60,
    "Fire Blue": 60,
    "Wealth Bitcoin Orange": 60,
    "Hope Yellow": 59,
    "Runestone Red": 59,
    "Birch White": 58,
    "Hope White": 58,
    "Stone Red": 57,
    "Fire White": 56,
    "Wealth Purple": 56,
    "Hope Bicoin Orange": 55,
    "Runestone Purple": 55,
    "Stone Purple": 55,
    "Sun Purple": 55,
    "Earth Bitcoin Orange": 54,
    "Birch Bitcoin Orange": 53,
    "Birch Green": 53,
    "Birch Purple": 53,
    "Fire Green": 53,
    "Ride Green": 53,
    "Stone Yellow": 53,
    "Wealth Green": 53,
    "Wealth Red": 53,
    "Birch Yellow": 52,
    "Earth Blue": 52,
    "Earth Red": 52,
    "Fire Bitcoin Orange": 52,
    "Fire Red": 52,
    "Ride Yellow": 52,
    "Ride Red": 51,
    "Ride White": 51,
    "Sun White": 51,
    "Wealth White": 51,
    "Hope Purple": 50,
    "Stone Green": 50,
    "Wealth Yellow": 50,
    "Hope Red": 49,
    "Stone Blue": 49,
    "Sun Blue": 49,
    "Earth White": 48,
    "Ride Bitcoin Orange": 48,
    "Runestone Bitcoin Orange": 48,
    "Earth Green": 47,
    "Runestone Blue": 47,
    "Runestone White": 47,
    "Sun Bitcoin Orange": 47,
    "Sun Yellow": 46,
    "Sun Green": 45,
    "Wealth Blue": 45,
    "Birch Blue": 44,
    "Earth Purple": 44,
    "Earth Yellow": 44,
    "Stone White": 43,
    "Stone Bitcoin Orange": 42,
    "Hope Green": 38,
  },
  House: {
    "Earth": 1111,
    "Fire": 1111,
    "Water": 1111,
  },
};

const EARS = { Pink: 1671, Grey: 1662 };

module.exports = { TOTAL, COUNTS, EARS };
