// Generated by tools/adventure/bundle.js. Do not edit: edit src/adventure/*.js and rebuild.
// The game rules live in one place and are shared by the browser and by node, so a fight the
// player sees is the same fight a server can recompute.

const registry = {};
const cache = {};
function require(id) {
  const name = String(id).replace(/^\.\//, '');
  if (cache[name]) return cache[name].exports;
  const factory = registry[name];
  if (!factory) throw new Error('adventure-core: no module ' + name);
  const module = { exports: {} };
  cache[name] = module;
  factory(module, module.exports, require);
  return module.exports;
}

registry["counts.gen"] = function (module, exports, require) {
'use strict';
// The allele universe of the Alpha collection, as counts. 178 heritable alleles over six loci,
// plus Ears, which is the sex locus and not a trait.
//
// Counts only. Every dominance fact in the game is derived from them at load by windowsFor(), so
// there is exactly one place where the one-third rule lives and no second table to keep in step.
// Regenerate with tools/adventure/alleles.js if the collection is ever extended.

const TOTAL = 3333;

const COUNTS = {
  Background: {
    "Purple": 242,
    "Yellow": 229,
    "Black": 225,
    "Grey": 218,
    "Red": 216,
    "Cool Green": 214,
    "Blocks": 212,
    "Sky Blue": 210,
    "Blue": 205,
    "Pink": 191,
    "Lemon": 188,
    "Blue Sky": 157,
    "Pink Sky": 130,
    "Emerald": 129,
    "Fuchsia": 118,
    "Sea Green": 116,
    "Bitcoin Orange": 92,
    "Night Sky": 90,
    "Punk": 61,
    "Zombie": 46,
    "Spectrum": 44,
  },
  Body: {
    "Sand": 191,
    "Dark Grey": 180,
    "Grey": 178,
    "Brown": 174,
    "Chocolate": 167,
    "Green": 166,
    "Ginger": 164,
    "Bitcoin Orange": 161,
    "White": 160,
    "Burmilla": 153,
    "Caramel": 152,
    "Red": 152,
    "Yellow": 152,
    "Au Lait": 150,
    "Cream": 147,
    "Blue": 145,
    "Pink": 145,
    "Bengal": 96,
    "Tortie": 71,
    "Harlequin Cream": 48,
    "Harlequin Ginger": 47,
    "Light Calico": 45,
    "Harlequin Earth": 44,
    "Harlequin Pink": 40,
    "Tiger": 39,
    "Oreo": 38,
    "Harlequin Lava": 31,
    "Cow": 27,
    "Harlequin Lime": 26,
    "Harlequin Monster": 23,
    "Harlequin Poison": 11,
    "Harlequin Lava Lamp": 10,
  },
  Collar: {
    "Red": 249,
    "Purple": 235,
    "Yellow": 234,
    "Green": 233,
    "Emerald": 231,
    "Bitcoin Orange": 228,
    "Black": 226,
    "Fuchsia": 226,
    "Sea Green": 220,
    "Dark Grey": 219,
    "Lemon": 218,
    "Blue": 212,
    "Sky Blue": 211,
    "Pink": 196,
    "White": 195,
  },
  Face: {
    "Sour": 111,
    "Perplexed Tiny Big Eyes": 110,
    "Cheeky": 108,
    "Happy Big Eyes": 103,
    "Happy": 102,
    "Sleeping Tif": 102,
    "Lover": 99,
    "Grumpy": 98,
    "Orange Glasses": 98,
    "Perplexed Tif": 98,
    "Satisfied": 98,
    "Perplexed Big Eyes": 97,
    "Perplexed Large": 97,
    "Sleepy Drool": 97,
    "UwU": 97,
    "sessalG D3": 97,
    "Crying": 96,
    "Perplexed Medium": 96,
    "Perplexed Small": 96,
    "Cooler": 91,
    "Stunned": 91,
    "3D Glasses": 90,
    "Laughing": 90,
    "Stunned Tif": 90,
    "Happy Big Mouth": 89,
    "Pink Glasses": 88,
    "Perplexed Tiny": 87,
    "Grumpier": 84,
    "Sky Blue Glasses": 81,
    "Happy Tif": 80,
    "Cool": 77,
    "Shiny Eyes Happy": 52,
    "Shiny Eyes Drool": 51,
    "Rainbow Glasses": 49,
    "Big Laughing": 36,
    "Double Shocked": 36,
    "In Love": 36,
    "Cyber Punk": 26,
    "Lazer": 25,
    "Super Happy": 22,
    "Demon": 21,
    "Super Laser": 17,
    "Old TV": 15,
    "Rainbow": 9,
  },
  Rune: {
    "Fire Purple": 67,
    "Hope Blue": 67,
    "Ride Blue": 67,
    "Fire Yellow": 64,
    "Runestone Green": 64,
    "Sun Red": 64,
    "Runestone Yellow": 62,
    "Ride Purple": 61,
    "Birch Red": 60,
    "Fire Blue": 60,
    "Wealth Bitcoin Orange": 60,
    "Hope Yellow": 59,
    "Runestone Red": 59,
    "Birch White": 58,
    "Hope White": 58,
    "Stone Red": 57,
    "Fire White": 56,
    "Wealth Purple": 56,
    "Hope Bicoin Orange": 55,
    "Runestone Purple": 55,
    "Stone Purple": 55,
    "Sun Purple": 55,
    "Earth Bitcoin Orange": 54,
    "Birch Bitcoin Orange": 53,
    "Birch Green": 53,
    "Birch Purple": 53,
    "Fire Green": 53,
    "Ride Green": 53,
    "Stone Yellow": 53,
    "Wealth Green": 53,
    "Wealth Red": 53,
    "Birch Yellow": 52,
    "Earth Blue": 52,
    "Earth Red": 52,
    "Fire Bitcoin Orange": 52,
    "Fire Red": 52,
    "Ride Yellow": 52,
    "Ride Red": 51,
    "Ride White": 51,
    "Sun White": 51,
    "Wealth White": 51,
    "Hope Purple": 50,
    "Stone Green": 50,
    "Wealth Yellow": 50,
    "Hope Red": 49,
    "Stone Blue": 49,
    "Sun Blue": 49,
    "Earth White": 48,
    "Ride Bitcoin Orange": 48,
    "Runestone Bitcoin Orange": 48,
    "Earth Green": 47,
    "Runestone Blue": 47,
    "Runestone White": 47,
    "Sun Bitcoin Orange": 47,
    "Sun Yellow": 46,
    "Sun Green": 45,
    "Wealth Blue": 45,
    "Birch Blue": 44,
    "Earth Purple": 44,
    "Earth Yellow": 44,
    "Stone White": 43,
    "Stone Bitcoin Orange": 42,
    "Hope Green": 38,
  },
  House: {
    "Earth": 1111,
    "Fire": 1111,
    "Water": 1111,
  },
};

const EARS = { Pink: 1671, Grey: 1662 };

module.exports = { TOTAL, COUNTS, EARS };

};
registry["pool"] = function (module, exports, require) {
'use strict';
// The allele pool: ranks, co-dominance windows, expression and Second Form.
//
// One rule produces all of it. Two alleles at a locus are co-dominant when the rarer is at least a
// third as common as its partner; below that the commoner one is expressed and the rarer is carried
// invisibly. Nothing here is hand authored, so extending the collection cannot leave a stale table
// behind, and the numbers agree with src/genetics.js by construction rather than by review.
//
// Ranks run 0 (commonest) upward, ties broken on the name so two runs on the same data agree. That
// ordering is also the dominance order: outside its window, an allele is masked by every lower rank
// and masks every higher one.

const { TOTAL, COUNTS, EARS } = require('./counts.gen');

const LOCI = ['Background', 'Body', 'Collar', 'Face', 'Rune', 'House'];
const CODOMINANCE_RATIO = 1 / 3;

function build() {
  const out = {};
  for (const locus of LOCI) {
    const sorted = Object.entries(COUNTS[locus])
      .sort((x, y) => y[1] - x[1] || (x[0] < y[0] ? -1 : 1));
    const names = sorted.map(([v]) => v);
    const counts = sorted.map(([, c]) => c);
    const n = names.length;

    // The window is the contiguous run of ranks this allele does not mask and is not masked by.
    // Contiguity is a property of a descending-sorted list, not an assumption: if j is inside the
    // window and k lies between i and j, then count[k] is between them too, so k is inside as well.
    const windows = counts.map((c, i) => {
      let lo = i, hi = i;
      for (let j = 0; j < n; j++) {
        if (j === i) continue;
        const d = counts[j];
        if (Math.min(c, d) / Math.max(c, d) >= CODOMINANCE_RATIO) { lo = Math.min(lo, j); hi = Math.max(hi, j); }
      }
      return [lo, hi];
    });

    out[locus] = { names, counts, windows, n, index: new Map(names.map((v, i) => [v, i])) };
  }
  return out;
}

const POOL = build();

/** Rank of a named allele, or -1. Names come off chain, so an unknown one must not throw. */
function rankOf(locus, name) {
  const L = POOL[locus];
  const i = L ? L.index.get(name) : undefined;
  return i === undefined ? -1 : i;
}

function nameOf(locus, rank) { return POOL[locus].names[rank]; }
function countOf(locus, rank) { return POOL[locus].counts[rank]; }
function sizeOf(locus) { return POOL[locus].n; }
function windowOf(locus, rank) { return POOL[locus].windows[rank]; }

/** Are these two ranks close enough in frequency that neither masks the other? */
function coDominant(locus, r1, r2) {
  if (r1 === r2) return false;
  const [lo, hi] = POOL[locus].windows[r1];
  return r2 >= lo && r2 <= hi;
}

// --- expression -----------------------------------------------------------------------------

// A small non-cryptographic hash. Expression must be identical on the client and the server, so it
// cannot depend on anything platform specific, and it runs on every locus of every visible creature
// so it must be cheap. FNV-1a over the string, which is deterministic everywhere.
function hash32(s) {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h >>> 0;
}

/**
 * Which of a pair is expressed, and which is held back as Second Form.
 *
 * The draw for a co-dominant pair is seeded on the individual, so a creature never changes
 * appearance between two reads, and two full siblings with identical genomes can still express
 * differently because their ids differ. The pair itself is in the seed, so adding a locus later
 * cannot reshuffle the expression of the ones already decided.
 */
function express(locus, r1, r2, individualSeed) {
  if (r1 === r2) return { rank: r1, second: r1, mode: 'homozygous' };
  const lo = Math.min(r1, r2), hi = Math.max(r1, r2);
  if (coDominant(locus, r1, r2)) {
    const pick = (hash32(`${individualSeed}|${locus}|${lo}|${hi}`) & 1) ? hi : lo;
    return { rank: pick, second: pick === lo ? hi : lo, mode: 'codominant' };
  }
  // Masked: the commoner allele is the lower rank, and it always wins.
  return { rank: lo, second: hi, mode: 'masked' };
}

/** The visible creature, plus the form it would take on a Flip. */
function phenotype(genome, individualSeed) {
  const first = {}, second = {}, mode = {};
  for (const locus of LOCI) {
    const [a, b] = genome[locus];
    const e = express(locus, a, b, individualSeed);
    first[locus] = e.rank; second[locus] = e.second; mode[locus] = e.mode;
  }
  return { first, second, mode };
}

/** A founder shows what it is: homozygous everywhere, so it has no Second Form and cannot Flip. */
function canFlip(genome) {
  return LOCI.some((locus) => genome[locus][0] !== genome[locus][1]);
}

/** Names rather than ranks, for anything that has to be read by a person. */
function readable(form) {
  const out = {};
  for (const locus of LOCI) out[locus] = nameOf(locus, form[locus]);
  return out;
}

module.exports = {
  TOTAL, EARS, LOCI, CODOMINANCE_RATIO, POOL,
  rankOf, nameOf, countOf, sizeOf, windowOf,
  coDominant, hash32, express, phenotype, canFlip, readable,
};

};
registry["faces"] = function (module, exports, require) {
'use strict';
// The 44 Faces. A Face is a passive: it fires on its own and the player never activates one.
//
// THE RULE THIS TABLE OBEYS. An allele that can be masked is an allele you have to breed for, and
// breeding for a bigger number is a boring project. So every Face that can hide grants a RULE, and
// only Faces that cannot hide are allowed to be a flat number. The line is not a taste call: it is
// read off the collection by pool.js, and test/adventure-content.test.js fails the build if a
// hideable Face carries a flat modifier.
//
// That constraint bit hard. The first draft of this table had Super Happy at "+6 damage" against
// Happy's "+2", In Love at "+8 HP/turn" against Lover's "+3", Big Laughing at "+8" against
// Laughing's "+4": seven rare Faces that were their common cousin with the number doubled. All
// seven are rewritten below, and the ones that survived untouched (the Glasses, Old TV, the Lasers)
// are exactly the ones that were already rules.
//
// Four more were rewritten for a different reason. Grumpy/Grumpier are 98 and 84 copies, Cooler and
// Cool are 91 and 77: peers, not tiers. Presenting them as an upgrade ladder claims a rarity gap
// the data does not contain, so they are now two different rules of comparable weight.

// `kind` is checked by the test, `fx` is what the engine reads. Text is what the player sees, and
// it is the only description that ships: there is no second copy in the UI to fall out of step.
const F = (rank, name, kind, text, fx = {}) => ({ rank, name, kind, text, fx });

const FACES = [
  F(0,  'Sour',                    'rule', "Sour. The opponent's Rune needs one extra turn to charge.", { opponentRuneSlower: 1 }),

  // Roughly a fifth of the pool is deliberately blank. A game where every cat has a trick is a game
  // where no trick reads, and the Perplexed tribe is what makes the others legible.
  F(1,  'Perplexed Tiny Big Eyes', 'none', 'No passive.'),
  F(2,  'Cheeky',                  'flat', '+2 damage.', { damageBonus: 2 }),
  F(3,  'Happy Big Eyes',          'flat', '+2 damage.', { damageBonus: 2 }),
  F(4,  'Happy',                   'flat', '+2 damage.', { damageBonus: 2 }),
  F(5,  'Sleeping Tif',            'rule', 'Asleep. Skips turn 1, then +6 Force.', { skipTurn1: true, forceAfterWaking: 6 }),
  F(6,  'Lover',                   'flat', '+3 HP each turn.', { regen: 3 }),
  F(7,  'Grumpy',                  'flat', '+3 damage if you were hit last turn.', { damageBonusIfHit: 3 }),
  F(8,  'Orange Glasses',          'rule', "Glasses. You see the opponent's Second Form.", { seeSecondForm: true }),
  F(9,  'Perplexed Tif',           'none', 'No passive.'),
  F(10, 'Satisfied',               'flat', '+2 damage.', { damageBonus: 2 }),
  F(11, 'Perplexed Big Eyes',      'none', 'No passive.'),
  F(12, 'Perplexed Large',         'none', 'No passive.'),
  F(13, 'Sleepy Drool',            'rule', 'Asleep. Skips turn 1, then +6 Force.', { skipTurn1: true, forceAfterWaking: 6 }),
  F(14, 'UwU',                     'flat', '+2 damage.', { damageBonus: 2 }),

  // 3D Glasses written backwards, and it was in the artwork before any of this was designed. At 97
  // copies it is a common face, so its effect has to be strange rather than strong: useless against
  // a Perplexed, ruinous against a rare Face. It also makes a junk common the natural counter to
  // the nine-copy grail. Do not put this in the in-game help. Let it be found.
  F(15, 'sessalG D3',              'rule', 'Mirror. Face passives are swapped between both fighters for the whole fight.', { mirrorFaces: true }),

  F(16, 'Crying',                  'flat', 'Heals 4 HP each time you take damage.', { healOnDamage: 4 }),
  F(17, 'Perplexed Medium',        'none', 'No passive.'),
  F(18, 'Perplexed Small',         'none', 'No passive.'),
  F(19, 'Cooler',                  'flat', '-2 damage taken.', { damageReduction: 2 }),
  F(20, 'Stunned',                 'rule', 'The first hit you take is halved.', { firstHitTaken: 'halve' }),
  F(21, '3D Glasses',              'rule', "Glasses. You see the opponent's Second Form.", { seeSecondForm: true }),
  F(22, 'Laughing',                'flat', '+4 damage after the opponent misses.', { damageAfterMiss: 4 }),
  F(23, 'Stunned Tif',             'rule', 'The first hit you take is halved.', { firstHitTaken: 'halve' }),
  F(24, 'Happy Big Mouth',         'flat', '+2 damage.', { damageBonus: 2 }),
  F(25, 'Pink Glasses',            'rule', "Glasses. You see the opponent's Second Form.", { seeSecondForm: true }),
  F(26, 'Perplexed Tiny',          'none', 'No passive.'),

  // 84 copies against Grumpy's 98. Peers, so a different rule rather than a bigger one.
  F(27, 'Grumpier',                'rule', 'Grudge. The first fighter to hit you loses 2 Force for the rest of the fight.', { grudge: 2 }),

  F(28, 'Sky Blue Glasses',        'rule', "Glasses. You see the opponent's Second Form.", { seeSecondForm: true }),
  F(29, 'Happy Tif',               'flat', '+2 damage.', { damageBonus: 2 }),

  // 77 against Cooler's 91. Immunity to the arena is the counter to the four Backgrounds that have
  // a rule at all, which makes Cool a pre-combat answer rather than a slightly better Cooler.
  F(30, 'Cool',                    'rule', 'Unbothered. Arena rules do not apply to you.', { arenaImmune: true }),

  // Initiative decides who imposes the arena, so this is the one Face that reaches into team
  // composition. It beats a Tuned collar, and Cow's Placid beats it back.
  F(31, 'Shiny Eyes Happy',        'rule', 'Wide awake. You act first, whatever the collars say.', { alwaysFirst: true }),

  F(32, 'Shiny Eyes Drool',        'rule', "Dreaming. Skips turn 1, then copies the opponent's Face for the rest of the fight.", { skipTurn1: true, copyFaceOnWaking: true }),
  F(33, 'Rainbow Glasses',         'rule', "Prism lenses. You see the opponent's entire genome.", { seeGenome: true }),

  // --- from here down, every Face can be masked, so every Face is a rule -----------------------

  F(34, 'Big Laughing',            'rule', 'Infectious. When the opponent misses, they miss their next attack too.', { contagiousMiss: true }),
  F(35, 'Double Shocked',          'rule', "Both fighters' first attack of the fight misses.", { bothMissFirst: true }),
  F(36, 'In Love',                 'rule', 'Devotion. The first time you would fall, you stand at 1 HP instead.', { standAtOne: true }),
  F(37, 'Cyber Punk',              'rule', 'Your Rune charges one turn faster.', { runeChargeFaster: 1 }),
  F(38, 'Lazer',                   'rule', 'Ignores Armor.', { ignoreArmor: true }),
  F(39, 'Super Happy',             'rule', 'Nothing sticks. Burn, Poison and Static expire on you immediately.', { nothingSticks: true }),
  F(40, 'Demon',                   'rule', 'Below 40% HP, the arena becomes your Background for the rest of the fight.', { arenaBecomesMineBelow: 0.40 }),
  F(41, 'Super Laser',             'rule', 'Ignores Armor and Shields.', { ignoreArmor: true, ignoreShield: true }),
  F(42, 'Old TV',                  'rule', "Static. The opponent's Rune misfires: it resolves as a random family instead of its own.", { staticRune: true }),

  // Nine copies. The triangle is the first thing the game teaches and the last thing this removes.
  F(43, 'Rainbow',                 'rule', 'Prism. The House triangle does not apply to you: every matchup is favourable.', { prism: true }),
];

const BY_NAME = new Map(FACES.map((f) => [f.name, f]));
const faceAt = (rank) => FACES[rank];
const faceNamed = (name) => BY_NAME.get(name) || null;

module.exports = { FACES, faceAt, faceNamed };

};
registry["bodies"] = function (module, exports, require) {
'use strict';
// The 32 Bodies. A Body is the stat block: HP, Force, Armor, plus at most one extra rule.
//
// THE BUDGET. Raw stats are scored HP + 4*Force + 9*Armor, and the extra rule is priced too, because
// a table that only budgets the numbers will always drift: the first draft rated Harlequin Monster
// the weakest body in the game at 114 while handing it uncapped Force growth, which over an average
// five turn fight is worth more than any stat line on the list. Rules now carry a `worth`, the test
// checks stats + worth, and Monster's growth is capped at +10 so the price is a fact and not a guess.
//
// Oreo also moved. It sat at 158, the highest budget of the 32, on Armor 6, which is punishing
// against the low Force bodies and invisible against the high ones. Armor 5 and 58 HP puts it at
// the top of the band instead of outside it.
//
// The 17 solid colours share one line on purpose. They are 52% of the collection and they are the
// baseline every rule is read against; giving each its own spread would be 17 numbers to learn for
// no decision gained.

const { POOL } = require('./pool');

const B = (rank, name, hp, force, armor, rule = null) => ({
  rank, name, hp, force, armor,
  rule,                                    // { text, worth, fx }
  budget: hp + 4 * force + 9 * armor + (rule ? rule.worth : 0),
});

// Rule prices, in budget points, stated once so they can be argued with.
//   14  a free Rune cast, or a free extra action
//   12  a per-turn drain or a free Flip
//   10  reactive damage
//    8  an unmissable opener
//    6  a narrow immunity, or a conditional reduction
//    5  a heal that depends on the opponent's choice
//    0  variance with no expected gain
//   -8  a permanent downside
const R = (text, worth, fx) => ({ text, worth, fx });

const SOLID = POOL.Body.names.slice(0, 17);

const BODIES = [
  ...SOLID.map((name, i) => B(i, name, 60, 13, 3)),

  B(17, 'Bengal',              52, 16, 2),
  B(18, 'Tortie',              66, 11, 4),

  // --- from here down, every Body can be masked, so every Body carries a rule ------------------

  B(19, 'Harlequin Cream',     58, 14, 2, R('Your first Rune each fight charges instantly.', 14, { firstRuneFree: true })),
  B(20, 'Harlequin Ginger',    58, 14, 2, R('Afterimage. The turn after you Flip, you act twice.', 14, { doubleTurnAfterFlip: true })),
  B(21, 'Light Calico',        66, 10, 4, R('Heals 5 HP when the opponent Flips.', 5, { healOnOpponentFlip: 5 })),
  B(22, 'Harlequin Earth',     62, 12, 3, R('Immune to Burn.', 6, { immuneBurn: true })),
  B(23, 'Harlequin Pink',      56, 15, 2, R('Flip costs no turn.', 12, { freeFlip: true })),
  B(24, 'Tiger',               40, 20, 1, R('Pounce. Your first attack cannot miss and cannot be shielded.', 8, { unmissableOpener: true })),
  B(25, 'Oreo',                58, 10, 5, R('Layered. The first attack against you each turn is reduced by 4.', 6, { firstAttackPerTurnReduction: 4 })),
  B(26, 'Harlequin Lava',      54, 15, 2, R('Burns anyone who hits you: 3 damage per turn for 1 turn.', 10, { burnAttacker: { amount: 3, turns: 1 } })),

  // 90 HP has to cost something, and losing the arena is a real cost rather than a smaller number.
  B(27, 'Cow',                 90,  8, 3, R('Placid. You never act first, whatever the collars say.', -8, { neverFirst: true })),

  B(28, 'Harlequin Lime',      56, 13, 3, R('Regenerates 3 HP per turn.', 12, { regen: 3 })),
  B(29, 'Harlequin Monster',   48, 12, 2, R('+2 Force every turn, up to +10.', 20, { forcePerTurn: 2, forceCap: 10 })),
  B(30, 'Harlequin Poison',    50, 13, 3, R('Poisons on contact: every hit landed on you costs the attacker 2 Force.', 12, { poisonAttacker: 2 })),

  // Ten copies, and deliberately unplayable in a planned way. Do not smooth this.
  B(31, 'Harlequin Lava Lamp', 60, 13, 3, R('All three stats reroll by up to 40% each turn.', 0, { rerollStats: 0.40 })),
];

const BY_NAME = new Map(BODIES.map((b) => [b.name, b]));
const bodyAt = (rank) => BODIES[rank];
const bodyNamed = (name) => BY_NAME.get(name) || null;

module.exports = { BODIES, bodyAt, bodyNamed };

};
registry["backgrounds"] = function (module, exports, require) {
'use strict';
// The 21 Backgrounds. The Background of whoever holds initiative becomes the arena for the whole
// fight, so this is a decision made before the fight starts (which cat do I send?) and never during
// it. That is where the complexity belongs: team composition costs the player no reading time.
//
// Seventeen of the twenty-one are decor. Only the three that can be masked carry a rule, plus Night
// Sky, which sits one rank above the line and is the tutorial's way of showing that arenas exist at
// all before any of them matters.

const { POOL } = require('./pool');

const G = (rank, name, text, fx = {}) => ({ rank, name, text, fx, decor: !Object.keys(fx).length });

const PLAIN = POOL.Background.names.slice(0, 17);

const BACKGROUNDS = [
  ...PLAIN.map((name, i) => G(i, name, 'Decor. No arena rule.')),

  G(17, 'Night Sky', 'Both sides miss one attack in six.', { missChance: 1 / 6 }),
  G(18, 'Punk',      'All damage varies by up to 50%.',    { damageVariance: 0.50 }),
  G(19, 'Zombie',    'Nobody can die during the first two turns.', { noDeathBefore: 3 }),

  // Paired with a Rainbow face this is the strongest cat in the game, and not one number was
  // written for it. It is the sum of two rules that were already there.
  G(20, 'Spectrum',  'Only the side that imposed the arena keeps its Face passive.', { imposerKeepsFace: true }),
];

const BY_NAME = new Map(BACKGROUNDS.map((b) => [b.name, b]));
const backgroundAt = (rank) => BACKGROUNDS[rank];
const backgroundNamed = (name) => BY_NAME.get(name) || null;

module.exports = { BACKGROUNDS, backgroundAt, backgroundNamed };

};
registry["runes"] = function (module, exports, require) {
'use strict';
// The 63 Runes are 9 families times 7 colours. The player learns nine effects, never sixty three:
// colour decides Tuning with the Collar and nothing else, so it never touches power.
//
// The families are named Fire and Earth, which are also House names. That collision is deliberate
// and there is deliberately NO synergy between them: a Fire rune on a Fire house does nothing
// special. A synergy would quietly penalise House Water, which has no rune family of its own.
//
// One data note that costs three cats if it is missed. Fifty five Alphas carry the rune
// "Hope Bicoin Orange", a typo in the collection for "Hope Bitcoin Orange". Parse the colour off
// the last word and those runes read as a colour called "Orange" that no collar can match, so three
// Alphas with a Bitcoin Orange collar silently lose their Tuned status. colourOf() below folds the
// typo, and keeps the original string, which is what the chain says and what must be matched on.

const COLOURS = ['Red', 'Purple', 'Yellow', 'Green', 'Blue', 'White', 'Bitcoin Orange'];

const FAMILIES = {
  Fire:      { text: 'Burn. +5 damage per turn for 2 turns.',                     fx: { burn: { amount: 5, turns: 2 } } },
  Sun:       { text: 'Heal 20 HP.',                                               fx: { heal: 20 } },
  Hope:      { text: 'Shield. Fully negates the next incoming attack.',           fx: { shield: true } },
  Ride:      { text: 'Surge. Attack twice this turn.',                            fx: { extraAttack: 1 } },
  Stone:     { text: '+4 Armor for the rest of the fight.',                       fx: { armor: 4 } },
  Earth:     { text: 'Riposte. Returns the next hit you take, in full.',          fx: { riposte: true } },
  Birch:     { text: 'Growth. +3 Force, and it stacks each time you cast it.',    fx: { force: 3 } },

  // No combat effect at all, and that is the point: it is the farmer's rune, and it makes loadout
  // a real question without adding a rule to combat.
  Wealth:    { text: 'No combat effect. Doubles every reward on victory.',        fx: { doubleRewards: true } },

  Runestone: { text: "Echo. Replays the last Rune cast, including the opponent's.", fx: { echo: true } },
};

const CHARGE_BASE = 4;   // turns
const CHARGE_TUNED = 2;

/** Split an on-chain rune name into family and colour, folding the Bicoin typo. */
function parseRune(name) {
  const s = String(name || '');
  const tail2 = s.split(' ').slice(-2).join(' ');
  if (tail2 === 'Bitcoin Orange' || tail2 === 'Bicoin Orange') {
    return { family: s.slice(0, s.length - tail2.length).trim(), colour: 'Bitcoin Orange', raw: s };
  }
  const i = s.lastIndexOf(' ');
  return i < 0 ? { family: s, colour: null, raw: s } : { family: s.slice(0, i), colour: s.slice(i + 1), raw: s };
}

const colourOf = (name) => parseRune(name).colour;
const familyOf = (name) => parseRune(name).family;
const effectOf = (name) => FAMILIES[parseRune(name).family] || null;

/** A collar and a rune are Tuned when they name the same colour. */
const isTuned = (collarName, runeName) => colourOf(runeName) === collarName;

/** Turns to charge, before any Face modifier. */
const chargeTurns = (tuned) => (tuned ? CHARGE_TUNED : CHARGE_BASE);

module.exports = {
  COLOURS, FAMILIES, CHARGE_BASE, CHARGE_TUNED,
  parseRune, colourOf, familyOf, effectOf, isTuned, chargeTurns,
};

};
registry["combat"] = function (module, exports, require) {
'use strict';
// Adventure Mode combat: three buttons, one deterministic reducer.
//
// Pure. No DB, no clock, no randomness beyond the seed the caller supplies, so a whole fight
// replays from (fighters, actions, seed) and anyone can recompute a result rather than believe it.
// That matters more here than it looks: the only thing worth claiming in this game is a rare cat,
// and a claim nobody can check is worth nothing.
//
// INITIATIVE MOVED, AND IT MATTERS. The first design gave initiative to the rarer Collar. Collar is
// the flattest locus in the collection, 249 down to 195, and it has no dominance at all, so that
// rule handed a permanent advantage (act first, and therefore impose your Background) to White, on
// a rarity gap of 1.28x. It also broke the game's own promise that a rare allele grants a rule and
// never an advantage. Initiative now goes to the Tuned collar, which already pays for itself: Tuned
// charges its Rune in two turns instead of four, and Mute takes +2 Armor in exchange. Ties fall to
// the lighter cat, then to the seeded flip. Two alleles override the whole chain, one upward
// (Shiny Eyes Happy) and one downward (Cow), and both are visible on the sprite.

const { LOCI, phenotype, canFlip, nameOf, rankOf } = require('./pool');
const { faceAt } = require('./faces');
const { bodyAt } = require('./bodies');
const { backgroundAt } = require('./backgrounds');
const RUNES = require('./runes');

// Water douses Fire, Fire scorches Earth, Earth swallows Water.
const BEATS = { Water: 'Fire', Fire: 'Earth', Earth: 'Water' };
const FAVOURABLE = 1.5, NEUTRAL = 1.0, UNFAVOURABLE = 0.75;

const MUTE_ARMOR = 2;

// A fight has a horizon, and it needs one. Damage has a floor of 1, several Faces and Bodies
// regenerate 3 per turn, and Oreo's layered reduction sits on top of its Armor: put those together
// and two ordinary cats can reach a state where neither can ever land the killing blow. Found by
// running two hundred random pairings, not by reading the table. Twenty turns is roughly four times
// the median fight, so it never interrupts a real one; when it fires, the healthier cat wins, which
// is the honest reading of what happened.
const TURN_LIMIT = 20;
const FLIP_FAIL_VIGOR = 50;      // below this a Flip fails one time in three
const FLIP_FAIL_CHANCE = 1 / 3;

// --- deterministic draws --------------------------------------------------------------------

// Fights are short and every draw must be reproducible from the seed alone, independent of how many
// draws came before, so each one hashes (seed, label) rather than advancing a stream. A replay that
// skips a branch therefore cannot desynchronise the ones after it.
function draw(seed, label) {
  let h = 0x811c9dc5;
  const s = `${seed}|${label}`;
  for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 0x01000193) >>> 0; }
  return (h >>> 8) / 0x1000000;
}

// --- fighters -------------------------------------------------------------------------------

function formOf(ranks) {
  return {
    body: bodyAt(ranks.Body),
    face: faceAt(ranks.Face),
    background: backgroundAt(ranks.Background),
    collar: nameOf('Collar', ranks.Collar),
    rune: nameOf('Rune', ranks.Rune),
    house: nameOf('House', ranks.House),
  };
}

/**
 * Build a fighter from a genome. `vigor` scales maxHP only: it is not an allele, it never changes
 * what a lineage can carry, and it is the one knob difficulty is allowed to touch (§8.12).
 */
function createFighter({ id, name, genome, vigor = 100, catnip = 0 }) {
  const { first, second } = phenotype(genome, id);
  const f = formOf(first);
  const hpScale = vigor >= 100 ? 1 : Math.max(0.4, 0.6 + vigor / 250);
  const tuned = RUNES.isTuned(f.collar, f.rune);

  return {
    id, name, genome, vigor, catnip,
    firstRanks: first, secondRanks: second,
    ranks: { ...first },
    form: 'first',
    canFlip: canFlip(genome),
    hasFlipped: false,
    hpScale,
    maxHp: Math.round(f.body.hp * hpScale),
    hp: Math.round(f.body.hp * hpScale),
    baseForce: f.body.force,
    forceMod: 0,
    baseArmor: f.body.armor + (tuned ? 0 : MUTE_ARMOR),
    armorMod: 0,
    tuned,
    runeCharge: 0,
    ...f,
    fx: {},                 // live effects: burn, shield, riposte, armor, force stacks
    flags: {},              // per fight memory: hitLastTurn, missedLast, firstHitTaken, stood
    lastRuneFamily: null,
  };
}

/** Re-derive the body-dependent numbers after a Flip, keeping the damage already taken. */
function reform(fighter, ranks) {
  const f = formOf(ranks);
  const tuned = RUNES.isTuned(f.collar, f.rune);
  const lost = fighter.maxHp - fighter.hp;
  Object.assign(fighter, f, {
    ranks: { ...ranks },
    tuned,
    maxHp: Math.round(f.body.hp * fighter.hpScale),
    baseForce: f.body.force,
    baseArmor: f.body.armor + (tuned ? 0 : MUTE_ARMOR),
  });
  fighter.hp = Math.max(1, fighter.maxHp - lost);
  return fighter;
}

// --- effective stats ------------------------------------------------------------------------

const forceOf = (x) => Math.max(1, x.baseForce + x.forceMod);
const armorOf = (x) => Math.max(0, x.baseArmor + x.armorMod);

/** The Face a fighter fights with: sessalG D3 swaps them, and Spectrum can take one away. */
function activeFace(state, side) {
  const me = state.f[side], you = state.f[1 - side];
  if (state.arena.fx.imposerKeepsFace && state.arenaOwner !== side && !me.face.fx.arenaImmune) {
    return faceAt(rankOf('Face', 'Perplexed Small'));   // a blank face, not a missing one
  }
  const mirrored = me.face.fx.mirrorFaces || you.face.fx.mirrorFaces;
  const borrowed = me.flags.copiedFace;
  if (borrowed) return borrowed;
  return mirrored ? you.face : me.face;
}

function houseMultiplier(state, side) {
  const me = state.f[side], you = state.f[1 - side];
  if (activeFace(state, side).fx.prism) return FAVOURABLE;
  if (BEATS[me.house] === you.house) return FAVOURABLE;
  if (BEATS[you.house] === me.house) return UNFAVOURABLE;
  return NEUTRAL;
}

// --- initiative -----------------------------------------------------------------------------

/**
 * Who acts first, and therefore whose Background becomes the arena.
 *
 * Tuned first, because a collar in phase with its rune is the readable version of "in tune", and
 * because Tuned already trades away Mute's +2 Armor to get it. Then the lighter cat, which makes
 * Cow slow and Tiger fast without a word of explanation. Then the seeded flip, so the answer is
 * never undefined. Two alleles jump the queue outright, and Cow's Placid loses to nothing.
 */
function initiative(a, b, seed) {
  const aFirst = a.face.fx.alwaysFirst, bFirst = b.face.fx.alwaysFirst;
  const aNever = !!(a.body.rule && a.body.rule.fx.neverFirst);
  const bNever = !!(b.body.rule && b.body.rule.fx.neverFirst);

  if (aNever !== bNever) return { side: aNever ? 1 : 0, why: 'placid' };
  if (aFirst !== bFirst) return { side: aFirst ? 0 : 1, why: 'wide awake' };
  if (a.tuned !== b.tuned) return { side: a.tuned ? 0 : 1, why: 'tuned collar' };
  if (a.maxHp !== b.maxHp) return { side: a.maxHp < b.maxHp ? 0 : 1, why: 'lighter' };
  return { side: draw(seed, 'initiative') < 0.5 ? 0 : 1, why: 'coin' };
}

// --- the fight ------------------------------------------------------------------------------

function startFight({ a, b, seed }) {
  const init = initiative(a, b, seed);
  const owner = init.side;
  const state = {
    seed, f: [a, b], turn: 1, toAct: owner, over: false, winner: null,
    arenaOwner: owner,
    arena: a.background && owner === 0 ? a.background : b.background,
    log: [],
  };
  state.arena = state.f[owner].background;

  emit(state, 'start', { arena: state.arena.name, first: owner, why: init.why });

  // Faces that act before anyone chooses anything.
  for (const s of [0, 1]) {
    const face = activeFace(state, s);
    if (face.fx.skipTurn1) { state.f[s].flags.asleep = true; emit(state, 'asleep', { side: s }); }
    if (face.fx.bothMissFirst) {
      state.f[0].flags.forceMiss = true; state.f[1].flags.forceMiss = true;
      emit(state, 'bothMiss', { side: s });
    }
    if (state.f[s].body.rule && state.f[s].body.rule.fx.firstRuneFree) {
      state.f[s].runeCharge = 99; emit(state, 'runeReady', { side: s, free: true });
    }
  }
  return state;
}

function emit(state, type, data) { state.log.push({ turn: state.turn, type, ...data }); }

/** The horizon. The cat holding the larger share of its own HP walks away. */
function timeUp(state) {
  const [a, b] = state.f;
  const fa = a.hp / a.maxHp, fb = b.hp / b.maxHp;
  state.over = true;
  state.winner = fa === fb ? (draw(state.seed, 'timeout') < 0.5 ? 0 : 1) : (fa > fb ? 0 : 1);
  state.timedOut = true;
  emit(state, 'timeout', { winner: state.winner, hp: [fa, fb] });
  return state;
}

function runeCost(state, side) {
  const me = state.f[side], you = state.f[1 - side];
  let cost = RUNES.chargeTurns(me.tuned);
  cost -= activeFace(state, side).fx.runeChargeFaster || 0;
  cost += activeFace(state, 1 - side).fx.opponentRuneSlower || 0;
  return Math.max(1, cost);
}

/** One attack. Returns the damage actually applied. */
function strike(state, side, label) {
  const me = state.f[side], you = state.f[1 - side];
  const myFace = activeFace(state, side), yourFace = activeFace(state, 1 - side);
  const pounce = me.body.rule && me.body.rule.fx.unmissableOpener && !me.flags.opened;
  me.flags.opened = true;

  // Misses: the arena's, the forced opening one, and Big Laughing's contagion.
  let miss = false;
  if (!pounce) {
    if (me.flags.forceMiss) { miss = true; me.flags.forceMiss = false; }
    else if (me.flags.contagiousMiss) { miss = true; me.flags.contagiousMiss = false; }
    else if (state.arena.fx.missChance && !myFace.fx.arenaImmune
             && draw(state.seed, `miss:${side}:${state.turn}:${label}`) < state.arena.fx.missChance) miss = true;
  }
  if (miss) {
    emit(state, 'miss', { side });
    you.flags.missedAgainstMe = true;
    if (yourFace.fx.contagiousMiss) me.flags.contagiousMiss = true;
    return 0;
  }

  let force = forceOf(me);
  if (me.flags.awakeBonus) force += me.flags.awakeBonus;
  let bonus = myFace.fx.damageBonus || 0;
  if (myFace.fx.damageBonusIfHit && me.flags.hitLastTurn) bonus += myFace.fx.damageBonusIfHit;
  if (myFace.fx.damageAfterMiss && me.flags.opponentMissed) bonus += myFace.fx.damageAfterMiss;

  const ignoreArmor = myFace.fx.ignoreArmor;
  let raw = force + bonus - (ignoreArmor ? 0 : armorOf(you));

  // Oreo reads the first attack of each turn, which is what makes it an answer to Ride's Surge.
  const layered = you.body.rule && you.body.rule.fx.firstAttackPerTurnReduction;
  if (layered && !you.flags.tookOneThisTurn) raw -= layered;
  you.flags.tookOneThisTurn = true;

  let dmg = Math.max(1, raw) * houseMultiplier(state, side);

  if (state.arena.fx.damageVariance && !myFace.fx.arenaImmune) {
    const v = state.arena.fx.damageVariance;
    dmg *= 1 - v + 2 * v * draw(state.seed, `var:${side}:${state.turn}:${label}`);
  }
  dmg = Math.max(1, Math.round(dmg));

  // Shields, and the two Faces that go through them.
  if (you.fx.shield && !(pounce || myFace.fx.ignoreShield)) {
    you.fx.shield = false;
    emit(state, 'shielded', { side: 1 - side });
    return 0;
  }

  const applied = damage(state, 1 - side, dmg, 'hit');
  emit(state, 'hit', { side, amount: applied, mult: houseMultiplier(state, side) });

  // Everything that answers back.
  if (you.fx.riposte) { you.fx.riposte = false; damage(state, side, applied, 'riposte'); emit(state, 'riposte', { side: 1 - side, amount: applied }); }
  if (yourFace.fx.healOnDamage) heal(state, 1 - side, yourFace.fx.healOnDamage);
  if (you.body.rule && you.body.rule.fx.burnAttacker && !me.body.rule?.fx.immuneBurn && !myFace.fx.nothingSticks) {
    me.fx.burn = { ...you.body.rule.fx.burnAttacker };
    emit(state, 'burned', { side, source: 'body' });
  }
  if (you.body.rule && you.body.rule.fx.poisonAttacker && !myFace.fx.nothingSticks) {
    me.forceMod -= you.body.rule.fx.poisonAttacker;
    emit(state, 'poisoned', { side, force: -you.body.rule.fx.poisonAttacker });
  }
  if (!you.flags.grudged && yourFace.fx.grudge) {
    you.flags.grudged = true; me.forceMod -= yourFace.fx.grudge;
    emit(state, 'grudge', { side, force: -yourFace.fx.grudge });
  }
  return applied;
}

function damage(state, side, amount, cause) {
  const x = state.f[side];
  const face = activeFace(state, side);
  let dmg = amount;
  if (cause === 'hit') {
    dmg = Math.max(0, dmg - (face.fx.damageReduction || 0));
    if (face.fx.firstHitTaken && !x.flags.firstHitTaken) {
      x.flags.firstHitTaken = true;
      dmg = face.fx.firstHitTaken === 'negate' ? 0 : Math.ceil(dmg / 2);
    }
  }
  x.hp -= dmg;
  if (cause === 'hit') x.flags.hitThisTurn = true;

  if (x.hp <= 0) {
    // Zombie holds the door for two turns, and Devotion holds it once.
    if (state.arena.fx.noDeathBefore && state.turn < state.arena.fx.noDeathBefore && !face.fx.arenaImmune) {
      x.hp = 1; emit(state, 'undying', { side });
    } else if (face.fx.standAtOne && !x.flags.stood) {
      x.flags.stood = true; x.hp = 1; emit(state, 'stood', { side });
    } else {
      x.hp = 0; state.over = true; state.winner = 1 - side;
      emit(state, 'down', { side });
    }
  }
  return dmg;
}

function heal(state, side, amount) {
  const x = state.f[side];
  const before = x.hp;
  x.hp = Math.min(x.maxHp, x.hp + amount);
  if (x.hp !== before) emit(state, 'heal', { side, amount: x.hp - before });
}

function castRune(state, side) {
  const me = state.f[side], you = state.f[1 - side];
  const myFace = activeFace(state, side), yourFace = activeFace(state, 1 - side);

  let family = RUNES.familyOf(me.rune);
  if (yourFace.fx.staticRune && !myFace.fx.nothingSticks) {
    const fams = Object.keys(RUNES.FAMILIES);
    family = fams[Math.floor(draw(state.seed, `static:${side}:${state.turn}`) * fams.length)];
    emit(state, 'static', { side, became: family });
  }
  if (family === 'Runestone' && state.lastRune) family = state.lastRune;

  const fx = (RUNES.FAMILIES[family] || {}).fx || {};
  state.lastRune = family;
  me.runeCharge = 0;
  emit(state, 'rune', { side, family });

  if (fx.heal) heal(state, side, fx.heal);
  if (fx.shield) me.fx.shield = true;
  if (fx.riposte) me.fx.riposte = true;
  if (fx.armor) me.armorMod += fx.armor;
  if (fx.force) me.forceMod += fx.force;
  if (fx.burn && !(you.body.rule && you.body.rule.fx.immuneBurn) && !yourFace.fx.nothingSticks) {
    you.fx.burn = { ...fx.burn }; emit(state, 'burned', { side: 1 - side, source: 'rune' });
  }
  if (fx.extraAttack) { strike(state, side, 'surge1'); if (!state.over) strike(state, side, 'surge2'); }
  if (fx.doubleRewards) state.f[side].flags.doubleRewards = true;
}

function attemptFlip(state, side) {
  const me = state.f[side];
  if (!me.canFlip) { emit(state, 'flipLocked', { side }); return false; }
  if (me.hasFlipped) { emit(state, 'flipSpent', { side }); return false; }
  if (me.catnip < 1) { emit(state, 'flipNoCatnip', { side }); return false; }

  me.catnip -= 1;
  me.hasFlipped = true;
  if (me.vigor < FLIP_FAIL_VIGOR && draw(state.seed, `flip:${side}:${state.turn}`) < FLIP_FAIL_CHANCE) {
    emit(state, 'flipFailed', { side, vigor: me.vigor });
    return false;
  }
  const before = { house: me.house, body: me.body.name };
  reform(me, me.form === 'first' ? me.secondRanks : me.firstRanks);
  me.form = me.form === 'first' ? 'second' : 'first';
  emit(state, 'flip', { side, from: before, to: { house: me.house, body: me.body.name } });

  const you = state.f[1 - side];
  if (you.body.rule && you.body.rule.fx.healOnOpponentFlip) heal(state, 1 - side, you.body.rule.fx.healOnOpponentFlip);
  if (me.body.rule && me.body.rule.fx.doubleTurnAfterFlip) me.flags.extraTurn = true;
  return true;
}

/** Start-of-turn upkeep for the side about to act, then hand it the turn. */
function upkeep(state, side) {
  const x = state.f[side], face = activeFace(state, side);
  x.flags.tookOneThisTurn = false;

  if (x.flags.asleep) {
    x.flags.asleep = false;
    if (face.fx.forceAfterWaking) { x.flags.awakeBonus = face.fx.forceAfterWaking; emit(state, 'awake', { side, force: face.fx.forceAfterWaking }); }
    if (face.fx.copyFaceOnWaking) { x.flags.copiedFace = activeFace(state, 1 - side); emit(state, 'copiedFace', { side, face: x.flags.copiedFace.name }); }
    return false;   // the skipped turn
  }
  if (x.fx.burn) {
    if (face.fx.nothingSticks) { x.fx.burn = null; emit(state, 'shrugged', { side, what: 'burn' }); }
    else {
      damage(state, side, x.fx.burn.amount, 'burn');
      emit(state, 'burn', { side, amount: x.fx.burn.amount });
      if (--x.fx.burn.turns <= 0) x.fx.burn = null;
    }
  }
  if (face.fx.regen) heal(state, side, face.fx.regen);
  if (x.body.rule && x.body.rule.fx.regen) heal(state, side, x.body.rule.fx.regen);
  if (x.body.rule && x.body.rule.fx.forcePerTurn) {
    const cap = x.body.rule.fx.forceCap;
    if (x.forceMod < cap) { x.forceMod = Math.min(cap, x.forceMod + x.body.rule.fx.forcePerTurn); emit(state, 'grew', { side, force: x.forceMod }); }
  }
  if (x.body.rule && x.body.rule.fx.rerollStats) {
    const v = x.body.rule.fx.rerollStats, b = bodyAt(x.ranks.Body);
    const r = (k) => 1 - v + 2 * v * draw(state.seed, `lamp:${side}:${state.turn}:${k}`);
    x.maxHp = Math.max(1, Math.round(b.hp * x.hpScale * r('hp')));
    x.hp = Math.min(x.hp, x.maxHp);
    x.baseForce = Math.max(1, Math.round(b.force * r('f')));
    x.baseArmor = Math.max(0, Math.round(b.armor * r('a'))) + (x.tuned ? 0 : MUTE_ARMOR);
    emit(state, 'reroll', { side, hp: x.maxHp, force: x.baseForce, armor: x.baseArmor });
  }
  if (face.fx.arenaBecomesMineBelow && !x.flags.arenaTaken && x.hp / x.maxHp < face.fx.arenaBecomesMineBelow) {
    x.flags.arenaTaken = true;
    state.arena = x.background; state.arenaOwner = side;
    emit(state, 'arenaSeized', { side, arena: state.arena.name });
  }
  if (x.runeCharge < 99) x.runeCharge += 1;
  return true;
}

/**
 * Play one action for the side to act. `action` is 'CLAW' | 'RUNE' | 'FLIP'.
 * Returns the state; read `state.log` for everything that happened.
 */
function act(state, action) {
  if (state.over) return state;
  const side = state.toAct, me = state.f[side], you = state.f[1 - side];
  const mark = state.log.length;

  me.flags.opponentMissed = !!you.flags.missedAgainstMe;
  you.flags.missedAgainstMe = false;

  const awake = upkeep(state, side);
  if (awake && !state.over) {
    if (action === 'RUNE' && me.runeCharge >= runeCost(state, side)) castRune(state, side);
    else if (action === 'FLIP') {
      const free = me.body.rule && me.body.rule.fx.freeFlip;
      attemptFlip(state, side);
      if (free && !state.over) strike(state, side, 'freeflip');
    } else strike(state, side, 'claw');

    if (me.flags.extraTurn && !state.over) {
      me.flags.extraTurn = false;
      me.flags.tookOneThisTurn = false;
      strike(state, side, 'afterimage');
    }
  }

  me.flags.hitLastTurn = !!me.flags.hitThisTurn;
  me.flags.hitThisTurn = false;
  state.actions = (state.actions || 0) + 1;
  if (!state.over) {
    state.toAct = 1 - side;
    if (state.actions % 2 === 0) state.turn += 1;
    if (state.turn > TURN_LIMIT) timeUp(state);
  }
  return Object.assign(state, { justHappened: state.log.slice(mark) });
}

/** What the UI is allowed to show about the opponent, decided by the Glasses tribe. */
function visionOf(state, side) {
  const face = activeFace(state, side);
  if (face.fx.seeGenome) return 'genome';
  if (face.fx.seeSecondForm) return 'second';
  return 'none';
}

module.exports = {
  BEATS, FAVOURABLE, NEUTRAL, UNFAVOURABLE, MUTE_ARMOR, FLIP_FAIL_VIGOR, TURN_LIMIT,
  draw, createFighter, initiative, startFight, act, activeFace, houseMultiplier,
  forceOf, armorOf, runeCost, visionOf,
};

};
registry["vivarium"] = function (module, exports, require) {
'use strict';
// The vivarium: an event queue, not a tick loop.
//
// The whole point of this file is that a five day absence and a five day presence produce the same
// world. Time is an integer count of minutes; every entity knows the minute of its next event; the
// queue pops in order. Reconnecting after 120 hours costs the same work as reconnecting after 121,
// and the result cannot be changed by touching the system clock, because every draw is seeded on
// (vivarium id, tick, entity id) rather than on Math.random.
//
// It is also the reason the player gets a logbook instead of a catch-up animation. Resolving the
// absence produces the events, in order, with timestamps; The Log is just that list rendered.
//
// BEDROCK IS NOT OPTIONAL. Left alone long enough this simulation kills everything, and a player
// who reconnects to sterile dirt does not reconnect twice. Seeds survive in the substrate, the last
// two Nubbins enter torpor rather than starve, and Roe waits in the silt. Recovery costs about six
// hours of play, which is a punishment. Extinction is not a punishment, it is an exit.

const MIN = 1;
const HOUR = 60;

const SPECIES = {
  Clover:   { mature: 20,  greensEvery: 30,  aquatic: false },
  Carrot:   { mature: 60,  greensEvery: 30,  aquatic: false },
  Duckweed: { mature: 40,  greensEvery: 0,   aquatic: true, oxygen: 2, algaeSlow: 0.5 },
  Catnip:   { mature: 180, catnipEvery: 360, aquatic: false },
};

const NUBBIN = { mealEvery: 30, dropEvery: 60, birthEvery: 12 * HOUR, starveAfter: 90 };
const GLIM   = { mealEvery: 60, roeEvery: 24 * HOUR, birthEvery: 12 * HOUR, starveAfter: 3 * HOUR };

const NITRATE_PER_DROPPING = 2;
// Irrigation is the burst, but it cannot be the ONLY path. A Glim starves in three hours and the
// basin only overflows when the player pours, so with irrigation alone the fish die every single
// cycle no matter how well the vivarium is run: the doc's own equilibrium arithmetic quietly
// assumed droppings converted continuously. They seep, slowly, at a quarter of the rate and only
// while the substrate is damp. Irrigation is still worth pouring for, it delivers the rest at once.
const SEEP_EVERY = 60;
const SEEP_PER_DROPPING = 0.5;
const NITRATE_PER_ALGAE = 4;
const ALGAE_EVERY = 60;
const EVAPORATE_EVERY = 30;
const HUMIDITY_DECAY_EVERY = 10;
const WILT_AFTER = 3 * HOUR;
const HUMIDITY_FLOOR = 30;

const FLOOD_THRESHOLD = 40;      // water poured in one action
const TORPOR_FLOOR = 3;          // Nubbins below this stop eating instead of dying
const ROE_HATCH_ALGAE = 4;
const REPLAY_CAP_DAYS = 30;

// --- deterministic draws --------------------------------------------------------------------

function draw(id, tick, entityId, salt = '') {
  let h = 0x811c9dc5;
  const s = `${id}|${tick}|${entityId}|${salt}`;
  for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 0x01000193) >>> 0; }
  return (h >>> 8) / 0x1000000;
}

// --- construction ---------------------------------------------------------------------------

function createVivarium(id, { tiles = 16, basinCap = 100, now = 0 } = {}) {
  return {
    id, tiles, basinCap,
    basin: { water: 0, nitrate: 0, algae: 0 },
    plants: [], nubbins: [], glims: [],
    greens: 0, droppings: 0, roe: 0, catnip: 0,
    humidity: 50,
    seedBank: {},
    cistern: null,
    lastTick: now,
    nextId: 1,
    log: [],
  };
}

const freeTiles = (v) => v.tiles - v.plants.filter((p) => p.alive && !SPECIES[p.species].aquatic).length;

function plant(v, species, at = v.lastTick) {
  if (!SPECIES[species]) return null;
  if (!SPECIES[species].aquatic && freeTiles(v) <= 0) return null;
  const p = {
    id: `p${v.nextId++}`, species, stage: 'seed',
    maturesAt: at + SPECIES[species].mature,
    nextYield: null, dryFor: 0, alive: true,
  };
  v.plants.push(p);
  return p;
}

function addNubbin(v, at = v.lastTick) {
  const n = { id: `n${v.nextId++}`, nextMeal: at + NUBBIN.mealEvery, nextDrop: at + NUBBIN.dropEvery,
              nextBirth: at + NUBBIN.birthEvery, hungrySince: null, torpid: false, alive: true };
  v.nubbins.push(n); return n;
}

function addGlim(v, at = v.lastTick) {
  const g = { id: `g${v.nextId++}`, nextMeal: at + GLIM.mealEvery, nextRoe: at + GLIM.roeEvery,
              nextBirth: at + GLIM.birthEvery, hungrySince: null, alive: true };
  v.glims.push(g); return g;
}

// --- player actions -------------------------------------------------------------------------

/**
 * Pour water.
 *
 * Two effects, deliberately split. Watering damps the substrate straight away, in proportion to
 * what you poured; only crossing the overflow lip washes the droppings into the basin as nitrate.
 * They were one effect at first and that was a trap: the lip sits at 80 units and pouring more than
 * 40 at once floods, so a player who did the obvious thing and emptied their flask got nothing at
 * all, twice, and then watched their plants wilt. Damp is cheap, nitrogen needs the flood tide.
 */
function pour(v, units, at = v.lastTick) {
  const events = [];
  const flooded = units > FLOOD_THRESHOLD;
  v.basin.water = Math.min(v.basinCap, v.basin.water + units);
  v.humidity = Math.min(100, v.humidity + units);
  for (const p of v.plants) p.dryFor = 0;
  events.push({ tick: at, type: 'poured', units, humidity: v.humidity });

  if (flooded) {
    const drowned = v.nubbins.filter((n) => n.alive).slice(0, 2);
    for (const n of drowned) { n.alive = false; events.push({ tick: at, type: 'drowned', id: n.id }); }
    v.basin.nitrate = Math.floor(v.basin.nitrate / 2);
    for (const p of v.plants) if (p.stage === 'seed') { p.alive = false; events.push({ tick: at, type: 'washedOut', id: p.id }); }
    events.push({ tick: at, type: 'flood' });
  }
  if (v.basin.water >= v.basinCap * 0.8) events.push(...irrigate(v, at));
  v.log.push(...events);
  return events;
}

function irrigate(v, at) {
  const events = [{ tick: at, type: 'irrigation' }];
  v.humidity = 100;
  for (const p of v.plants) p.dryFor = 0;
  if (v.droppings > 0) {
    const n = v.droppings * NITRATE_PER_DROPPING;
    v.basin.nitrate += n;
    events.push({ tick: at, type: 'nitrate', amount: n, from: v.droppings });
    v.droppings = 0;
  }
  return events;
}

// --- resolution -----------------------------------------------------------------------------

function nextEventOf(e, kind) {
  if (!e.alive) return Infinity;
  if (kind === 'plant') {
    if (e.stage === 'seed') return e.maturesAt;
    return e.nextYield === null ? Infinity : e.nextYield;
  }
  if (kind === 'nubbin') return Math.min(e.torpid ? Infinity : e.nextMeal, e.nextDrop, e.nextBirth);
  return Math.min(e.nextMeal, e.nextRoe, e.nextBirth);
}

/**
 * Advance the world to `nowTick`. Returns the log of everything that happened, in order, which is
 * exactly what The Log renders. O(events), not O(minutes x entities).
 */
function resolve(v, nowTick) {
  const events = [];
  const capped = Math.min(nowTick, v.lastTick + REPLAY_CAP_DAYS * 24 * HOUR);
  if (capped < nowTick) events.push({ tick: v.lastTick, type: 'dormancy', days: Math.floor((nowTick - capped) / (24 * HOUR)) });

  // World clocks, which do not belong to any entity.
  let nextEvap = v.lastTick + EVAPORATE_EVERY;
  let nextSeep = v.lastTick + SEEP_EVERY;
  let nextDry = v.lastTick + HUMIDITY_DECAY_EVERY;
  let nextAlgae = v.lastTick + ALGAE_EVERY;

  let guard = 0;
  while (guard++ < 200000) {
    let t = Infinity, pick = null;
    const consider = (tick, fn) => { if (tick < t) { t = tick; pick = fn; } };

    consider(nextEvap, () => { stepEvaporation(v, t, events); nextEvap = t + EVAPORATE_EVERY; });
    consider(nextDry,  () => { stepHumidity(v, t, events);   nextDry  = t + HUMIDITY_DECAY_EVERY; });
    consider(nextAlgae,() => { stepAlgae(v, t, events);      nextAlgae = t + ALGAE_EVERY; });
    consider(nextSeep, () => { stepSeep(v, t, events);       nextSeep = t + SEEP_EVERY; });
    for (const p of v.plants) consider(nextEventOf(p, 'plant'),  () => stepPlant(v, p, t, events));
    for (const n of v.nubbins) consider(nextEventOf(n, 'nubbin'), () => stepNubbin(v, n, t, events));
    for (const g of v.glims)   consider(nextEventOf(g, 'glim'),   () => stepGlim(v, g, t, events));

    if (!pick || t > capped) break;
    pick();
  }

  v.lastTick = nowTick;
  v.plants = v.plants.filter((p) => p.alive);
  bedrock(v, nowTick, events);
  v.log.push(...events);
  return events;
}

function stepEvaporation(v, t, events) {
  const dose = v.cistern && v.cistern.water > 0 ? Math.min(v.cistern.dosePerTick, v.cistern.water) : 0;
  if (dose) { v.cistern.water -= dose; v.basin.water = Math.min(v.basinCap, v.basin.water + dose); }
  const before = v.basin.water;
  v.basin.water = Math.max(0, v.basin.water - 1);
  if (before > 0 && v.basin.water === 0) events.push({ tick: t, type: 'basinDry' });
}

function stepHumidity(v, t, events) {
  v.humidity = Math.max(0, v.humidity - 1);
  if (v.humidity >= HUMIDITY_FLOOR) return;
  for (const p of v.plants) {
    if (!p.alive || SPECIES[p.species].aquatic) continue;
    p.dryFor += HUMIDITY_DECAY_EVERY;
    if (p.dryFor >= WILT_AFTER) {
      p.alive = false;
      v.seedBank[p.species] = Math.max(2, (v.seedBank[p.species] || 0) + 1);
      events.push({ tick: t, type: 'wilted', id: p.id, species: p.species });
    }
  }
}

function stepSeep(v, t, events) {
  if (v.droppings <= 0 || v.humidity < HUMIDITY_FLOOR) return;
  const n = Math.floor(v.droppings * SEEP_PER_DROPPING);
  if (n < 1) return;
  const spent = Math.ceil(n / NITRATE_PER_DROPPING);
  v.droppings -= spent;
  v.basin.nitrate += n;
  events.push({ tick: t, type: 'seep', amount: n });
}

function stepAlgae(v, t, events) {
  if (v.basin.water <= 0) return;
  const slow = v.plants.some((p) => p.alive && p.species === 'Duckweed' && p.stage === 'mature');
  const want = slow ? 1 : 2;
  let grew = 0;
  while (grew < want && v.basin.nitrate >= NITRATE_PER_ALGAE) { v.basin.nitrate -= NITRATE_PER_ALGAE; v.basin.algae += 1; grew++; }
  if (grew) events.push({ tick: t, type: 'algae', amount: grew });
  if (v.roe > 0 && v.basin.algae >= ROE_HATCH_ALGAE) {
    v.roe -= 1; addGlim(v, t);
    events.push({ tick: t, type: 'hatched', from: 'silt' });
  }
}

function stepPlant(v, p, t, events) {
  const sp = SPECIES[p.species];
  if (p.stage === 'seed') {
    p.stage = 'mature';
    p.nextYield = sp.greensEvery ? t + sp.greensEvery : (sp.catnipEvery ? t + sp.catnipEvery : null);
    events.push({ tick: t, type: 'matured', id: p.id, species: p.species });
    return;
  }
  if (sp.greensEvery) { v.greens += 1; p.nextYield = t + sp.greensEvery; events.push({ tick: t, type: 'greens', id: p.id }); }
  else if (sp.catnipEvery) { v.catnip += 1; p.nextYield = t + sp.catnipEvery; events.push({ tick: t, type: 'catnip', id: p.id }); }
}

function stepNubbin(v, n, t, events) {
  if (!n.torpid && t >= n.nextMeal) {
    if (v.greens > 0) {
      v.greens -= 1; n.hungrySince = null; n.nextMeal = t + NUBBIN.mealEvery;
      events.push({ tick: t, type: 'ate', id: n.id, what: 'greens' });
    } else {
      if (n.hungrySince === null) n.hungrySince = t;
      n.nextMeal = t + 10;
      if (t - n.hungrySince >= NUBBIN.starveAfter) {
        const alive = v.nubbins.filter((x) => x.alive).length;
        if (alive <= TORPOR_FLOOR - 1) { n.torpid = true; events.push({ tick: t, type: 'torpor', id: n.id }); }
        else { n.alive = false; events.push({ tick: t, type: 'starved', id: n.id, species: 'Nubbin' }); return; }
      }
    }
  }
  if (t >= n.nextDrop) { if (!n.torpid) { v.droppings += 1; events.push({ tick: t, type: 'dropping', id: n.id }); } n.nextDrop = t + NUBBIN.dropEvery; }
  if (t >= n.nextBirth) {
    n.nextBirth = t + NUBBIN.birthEvery;
    if (!n.torpid && n.hungrySince === null) { addNubbin(v, t); events.push({ tick: t, type: 'born', species: 'Nubbin' }); }
  }
}

function stepGlim(v, g, t, events) {
  if (t >= g.nextMeal) {
    if (v.basin.algae > 0) {
      v.basin.algae -= 1; g.hungrySince = null; g.nextMeal = t + GLIM.mealEvery;
      events.push({ tick: t, type: 'ate', id: g.id, what: 'algae' });
    } else {
      if (g.hungrySince === null) g.hungrySince = t;
      g.nextMeal = t + 15;
      if (t - g.hungrySince >= GLIM.starveAfter) {
        g.alive = false;
        // A corpse is nitrogen. This is what turns a fish die-off into an algae bloom twelve hours
        // later, and then into a second die-off. Nobody wrote the oscillation; it is the rules.
        v.basin.nitrate += 6;
        events.push({ tick: t, type: 'asphyxiated', id: g.id });
        return;
      }
    }
  }
  if (t >= g.nextRoe) { v.roe += 1; g.nextRoe = t + GLIM.roeEvery; events.push({ tick: t, type: 'roe', id: g.id }); }
  if (t >= g.nextBirth) {
    g.nextBirth = t + GLIM.birthEvery;
    if (g.hungrySince === null && v.basin.algae > 0) { addGlim(v, t); addGlim(v, t); events.push({ tick: t, type: 'born', species: 'Glim', count: 2 }); }
  }
}

/** The floor. Never lets the world reach a state a player cannot restart from. */
function bedrock(v, t, events) {
  v.nubbins = v.nubbins.filter((n) => n.alive);
  v.glims = v.glims.filter((g) => g.alive);
  for (const p of v.plants) if (!p.alive) v.seedBank[p.species] = Math.max(2, v.seedBank[p.species] || 0);
  for (const sp of Object.keys(v.seedBank)) v.seedBank[sp] = Math.max(2, v.seedBank[sp]);
  if (v.nubbins.length === 0 && v.roe === 0 && Object.keys(v.seedBank).length === 0) return;
  if (v.nubbins.length && v.nubbins.length < TORPOR_FLOOR) {
    for (const n of v.nubbins) if (!n.torpid) { n.torpid = true; events.push({ tick: t, type: 'torpor', id: n.id }); }
  }
}

/** Everything the player is shown at a glance, plus the one number that says how it is going. */
function snapshot(v) {
  const mature = v.plants.filter((p) => p.alive && p.stage === 'mature').length;
  const nubbins = v.nubbins.length, glims = v.glims.length;
  return {
    tiles: v.tiles, freeTiles: freeTiles(v), mature, nubbins, glims,
    water: v.basin.water, nitrate: v.basin.nitrate, algae: v.basin.algae,
    greens: v.greens, droppings: v.droppings, roe: v.roe, catnip: v.catnip,
    humidity: v.humidity,
    // The three verified ratios: one mature plant per Nubbin, two Nubbins per Glim.
    balance: { plantsPerNubbin: nubbins ? mature / nubbins : null, nubbinsPerGlim: glims ? nubbins / glims : null },
  };
}

module.exports = {
  HOUR, SPECIES, NUBBIN, GLIM, FLOOD_THRESHOLD, TORPOR_FLOOR, REPLAY_CAP_DAYS, SEEP_EVERY,
  createVivarium, plant, addNubbin, addGlim, pour, irrigate, resolve, snapshot, freeTiles, draw,
};

};
registry["hunt"] = function (module, exports, require) {
'use strict';
// Hunt mode: a small node graph, a stamina budget, and a way home.
//
// The one rule that matters here is negative. Wild Alphas draw their alleles at exact collection
// frequency and ADVANCED BIOMES NEVER CHANGE THAT. Biasing the wild pool toward rare alleles is the
// single easiest way to destroy this game: it turns the grail hunt from a season into a week, and
// every hidden allele in the vivarium stops being worth carrying. Difficulty scales on bot tier,
// wild Vigor and fights per run, all of which sit outside the genetic economy.
//
// The Strand is the other half of that bargain. A wild Alpha drops one, the PLAYER chooses which
// locus it samples, and the game returns one of the wild's two alleles at that locus. Choosing is
// not a convenience: with a random locus a large share of players never converge on a grail at all,
// because the reward has a tail longer than anyone's patience.

const { LOCI, POOL, sizeOf, nameOf } = require('./pool');
const { createFighter } = require('./combat');

const STAMINA_PER_ALPHA = 8;
const WATER_PER_ALPHA = 12;

const NODE_TABLE = [
  { type: 'dew',     weight: 15, water: 4 },
  { type: 'pool',    weight: 12, water: 8 },
  { type: 'spring',  weight: 8,  water: 14 },
  { type: 'seeds',   weight: 20 },
  { type: 'nubbin',  weight: 12 },
  { type: 'glim',    weight: 8 },
  { type: 'wild',    weight: 20 },
  { type: 'empty',   weight: 5 },
];

function draw(seed, label) {
  let h = 0x811c9dc5;
  const s = `${seed}|${label}`;
  for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 0x01000193) >>> 0; }
  return (h >>> 8) / 0x1000000;
}

function pickWeighted(table, r) {
  const total = table.reduce((s, x) => s + x.weight, 0);
  let acc = 0, target = r * total;
  for (const x of table) { acc += x.weight; if (target < acc) return x; }
  return table[table.length - 1];
}

/** Draw one allele at exact collection frequency. Never biased, at any biome, ever. */
function drawByFrequency(locus, r) {
  const counts = POOL[locus].counts;
  const total = counts.reduce((s, c) => s + c, 0);
  let acc = 0, target = r * total;
  for (let i = 0; i < counts.length; i++) { acc += counts[i]; if (target < acc) return i; }
  return counts.length - 1;
}

/**
 * A wild Alpha. Always a hybrid, which is how the player first sees a Flip happen at all, and how
 * they learn that the padlocked button on their own founder is a thing worth breeding for.
 */
function generateWild(seed, index, { vigor = 100, tier = 1 } = {}) {
  const genome = {};
  for (const locus of LOCI) {
    let a = drawByFrequency(locus, draw(seed, `w${index}:${locus}:a`));
    let b = drawByFrequency(locus, draw(seed, `w${index}:${locus}:b`));
    if (a === b) b = (b + 1) % sizeOf(locus);   // hybrid by construction
    genome[locus] = [a, b];
  }
  const f = createFighter({ id: `wild:${seed}:${index}`, name: 'Wild Alpha', genome, vigor, catnip: 1 });
  f.tier = tier;
  return f;
}

/** The map for one run. Procedural, seeded, and small enough to read in one glance. */
function generateHunt(seed, { nodes = 12, party = 1, biome = 'starter', tier = 1, wildVigor = 100, firstEver = false } = {}) {
  const list = [];
  for (let i = 0; i < nodes; i++) {
    // The first hunt is the bootstrap and it is scripted, because the vivarium starts as empty dirt
    // and a player who draws four Empty nodes has no game to come back to.
    // Stamina is 8 for a solo party, so the bootstrap has to deliver inside eight visits, not
    // twelve. A nest holds two Nubbins and a shoal three Glims on this run only.
    const forced = firstEver ? ['dew', 'seeds', 'nubbin', 'wild', 'pool', 'nubbin', 'glim', 'seeds', 'dew', 'nubbin', 'glim', 'spring'][i] : null;
    const t = forced ? NODE_TABLE.find((x) => x.type === forced) : pickWeighted(NODE_TABLE, draw(seed, `node:${i}`));
    list.push({
      index: i, type: t.type, water: t.water || 0, visited: false,
      seeds: t.type === 'seeds' ? (firstEver ? 3 : 1 + Math.floor(draw(seed, `seeds:${i}`) * 3)) : 0,
      wild: t.type === 'wild' ? { seed, index: i, tier, vigor: wildVigor } : null,
      yield: firstEver ? (t.type === 'nubbin' ? 2 : t.type === 'glim' ? 3 : 1) : 1,
    });
  }
  return {
    seed, biome, nodes: list, at: 0,
    stamina: STAMINA_PER_ALPHA * party,
    waterCap: WATER_PER_ALPHA * party,
    bag: { water: 0, seeds: 0, nubbins: 0, glims: 0, strands: [] },
    over: false,
  };
}

/** Move to a node and collect it. Costs one stamina; returns what happened. */
function visit(hunt, index) {
  if (hunt.over) return { error: 'the run is over' };
  const node = hunt.nodes[index];
  if (!node) return { error: 'no such node' };
  if (node.visited) return { error: 'already visited' };
  if (hunt.stamina <= 0) return { error: 'out of stamina' };

  hunt.stamina -= 1;
  node.visited = true;
  hunt.at = index;
  const got = { type: node.type };

  if (node.water) { const room = hunt.waterCap - hunt.bag.water; got.water = Math.min(node.water, room); hunt.bag.water += got.water; }
  if (node.seeds) { hunt.bag.seeds += node.seeds; got.seeds = node.seeds; }
  const many = node.yield || 1;
  if (node.type === 'nubbin') { hunt.bag.nubbins += many; got.nubbins = many; }
  if (node.type === 'glim') { hunt.bag.glims += many; got.glims = many; }
  if (node.type === 'wild') got.wild = generateWild(node.wild.seed, node.wild.index, { vigor: node.wild.vigor, tier: node.wild.tier });

  if (hunt.stamina <= 0) hunt.over = true;
  return got;
}

/**
 * Take a Strand off a defeated wild. The player names the locus; the game returns one of the two
 * alleles that wild carried there, at random. Single use.
 */
function takeStrand(hunt, wild, locus, seedSalt = '') {
  if (!LOCI.includes(locus)) return { error: 'not a locus' };
  const pair = wild.genome[locus];
  const rank = draw(`${wild.id}|${seedSalt}`, `strand:${locus}`) < 0.5 ? pair[0] : pair[1];
  const strand = { locus, rank, name: nameOf(locus, rank), from: wild.id };
  hunt.bag.strands.push(strand);
  return strand;
}

module.exports = {
  STAMINA_PER_ALPHA, WATER_PER_ALPHA, NODE_TABLE,
  draw, drawByFrequency, generateWild, generateHunt, visit, takeStrand,
};

};

export const pool = require('pool');
export const faces = require('faces');
export const bodies = require('bodies');
export const backgrounds = require('backgrounds');
export const runes = require('runes');
export const combat = require('combat');
export const vivarium = require('vivarium');
export const hunt = require('hunt');
